---
name: Build Statamic static site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git branch -D prod &>/dev/null || true
      - run: git checkout -b prod
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: npm i
      - run: npm run build
      - uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: composer
      - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
          --prefer-dist
      - run: php please key:generate
      - run: php please ssg:generate
        env:
          APP_URL: https://marccoup.uk
          APP_NAME: "Marcus Coupland"
          APP_ENV: production
      - run: cp -rv ./storage/app/static ./build
      - run: git add .
      - run: git config --global user.email "git-actions@marccoup.uk"
      - run: git config --global user.name "Actions"
      - run: git commit -m "Build `date`"
      - run: git push -u origin prod --force
      - run: 'curl "${{ secrets.DEPLOY_WEBHOOK }}" --header "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}"'
